apiVersion: v1
kind: Service
metadata:
  name: testapp1-service
  labels:
    app: testapp1-service
spec:
  type: ClusterIP
  selector:
    app: testapp1-pod
  ports:
    - port: 80
      targetPort: 80
